services:
  # 1. Backend Laravel (API)
  laravel-backend:
    build:
      context: ./server-laravel
      dockerfile: Dockerfile
    container_name: laravel-prod
    restart: always
    ports:
      - "80:80" 
    env_file:
      - ./server-laravel/.env 
    deploy:
      resources:
        limits:
          memory: 1G

  # 2. Sistema GLPI
  glpi:
    image: glpi/glpi:latest
    container_name: glpi-prod
    restart: always
    ports:
      - "8080:80" 
    environment:
      # Conexión directa a RDS
      - GLPI_DB_HOST=tu-instancia-rds.us-east-1.rds.amazonaws.com
      - GLPI_DB_NAME=glpi_db
      - GLPI_DB_USER=admin_rds
      - GLPI_DB_PASSWORD=tu_password_seguro
    volumes:
      # Uso de volumen nombrado para evitar problemas de permisos en Linux/EC2
      - glpi_data_prod:/var/www/html/glpi
  
  mailpit:
    image: axllent/mailpit
    container_name: mailpit-prod
    restart: always
    environment:
      - MP_UI_AUTH=${MAILPIT_UI_USER}:${MAILPIT_UI_PASS}
      - MP_DATA_FILE=/data/mailpit.db
    volumes:
      - mailpit_data:/data
    deploy:
      resources:
        limits:
          memory: 256M # Límite de seguridad para AWS

  # 4. Automatización con n8n
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-prod
    restart: always
    ports:
      - "5678:5678"
    environment:
      - NODE_ENV=production
      - N8N_HOST=n8n.elmerdev.com
      - WEBHOOK_URL=https://n8n.elmerdev.com/
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    volumes:
      - n8n_storage_prod:/home/node/.n8n
      # Eliminé el mapeo .:/data/project:ro porque en prod n8n no necesita ver tu código fuente, 
      # recibe el CSV de las pruebas por la red vía Webhook.
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - n8n

# Declaración de volúmenes manejados por Docker
volumes:
  glpi_data_prod:
  n8n_storage_prod:
  mailpit_data: