CREATE DATABASE IF NOT EXISTS `glpi_db` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `biblioteca` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `laravel_biblioteca` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root_pass' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'glpi_user'@'%' IDENTIFIED BY 'glpi_pass' WITH GRANT OPTION;

FLUSH PRIVILEGES;
